ORG 0000H
   LJMP MAIN
ORG 000BH			;INTERRUPT TIMER0
	 MOV TH0,#0F6H  ;DELAY FOR INTERUPPT 2.5mS
	 MOV TL0,#3CH
	 PUSH PSW
	 PUSH ACC ; Push the value of ACC onto the stack
	 CLR RS1	
	 SETB RS0 		; RB1
	 MOV P2,R2		;SELECT NO. OF LED
	 MOV P0,@R0		;DATA WHICH HAS TO BE SHOWN ON LED
	 INC R0
	 MOV A,R2
	 RL A
	 MOV R2,A
	 CJNE R0,#38H,L1
	 MOV R0,#30H
L1:  POP ACC
	 POP PSW
	 RETI 
	 
MAIN:MOV SP,#50H
	 MOV TMOD,#01H		;TIMER0
	 MOV TH0,#0F6H		;DELAY FOR INTERUPPT 2.5mS
	 MOV TL0,#3CH
	 MOV 08H,#30H
	 MOV 0AH,#01H
	 SETB TR0
	 SETB ET0
	 SETB EA
;-------OUTPUT 0--------
OP0: MOV DPTR,#MSG0
	 LCALL DISPLAY
	 LCALL SWITCH1
	 SJMP OP0
;-------OUTPUT 1--------	 
OP1: MOV DPTR,#MSG1		;STEADY MESSAGE
	 LCALL DISPLAY
	 LCALL SWITCH1
	 SJMP OP1
;-------OUTPUT 2-------------
OP2: MOV DPTR,#MSG1		;BLINKING MESSAGE
	 LCALL DISPLAY
	 LCALL DELAY
	 LCALL BLANK
	 LCALL DELAY
	 SJMP OP2
;-------OUTPUT 3-------------	 
OP3: MOV DPTR,#MSG2		;ROLLING THROUGH LEFT
	 MOV A,DPL
	 CLR C
	 ADD A,#16		
	 MOV DPL,A
	 MOV A,DPH
	 ADDC A,#00H
	 MOV DPH,A
	 MOV R3,#16
   LOOP3: 	 LCALL DISPLAY
	 LCALL DELAY
	 CLR C
     DEC DPL
     MOV A,DPH
     SUBB A,#00B
     MOV DPH,A
	 DJNZ R3,LOOP3
	 SJMP OP3
;-------OUTPUT 4-------------	  
OP4: MOV DPTR,#MSG2		;ROLLING THROUGH RIGHT
	 MOV R3,#16
   LOOP4:	 LCALL DISPLAY
	 LCALL DELAY
	 INC DPTR
	 DJNZ R3,LOOP4
	 SJMP OP4  
;-------OUTPUT 5-------------	 
OP5: MOV DPTR,#MSG1		;ODD NO. LED BLINKING OTHER'S STEADY
	 LCALL DISPLAY
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 LCALL BLANK
	 MOV R0,#31H
	 MOV R2,#01H
   LOOP5:	 LCALL DONE5
	 CJNE R2,#09H,LOOP5
	 LCALL DELAY
	 SJMP OP5
   DONE5:	 MOV A,R2
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R0,A
	 INC R0
	 INC R0
	 INC R2
	 INC R2
	 RET	 
;-------OUTPUT 6-------------	 
OP6: MOV DPTR,#MSG1		; EVEN NO. LED BLINKING OTHER'S STEADY
	 LCALL DISPLAY
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 LCALL BLANK
	 MOV R0,#30H
	 MOV R2,#00H
   LOOP6:	 LCALL DONE5
	 CJNE R2,#08H,LOOP6
	 LCALL DELAY
	 SJMP OP6
;-------OUTPUT 7------------- 
OP7:	 ;ROLLING MESSAGE OUTSIDE TO INSIDE
	 MOV DPTR,#MSG3
	 MOV 22H,#5
	 MOV A,DPL
	 ADD A,#4
	 MOV DPL,A
	 MOV 20H,DPL
	 MOV DPTR,#MSG4
	 MOV 21H,DPL
 HARDIK:MOV DPL,20H
	 LCALL LOOP71
	 MOV DPL,21H
	 LCALL LOOP72
	 DEC 20H
	 INC 21H
	 LCALL DELAY
	 DJNZ 22H,HARDIK
	 LCALL DELAY
	 SJMP OP7
	 
LOOP71:PUSH DPL
	    PUSH DPH
	    MOV R0,#30H
LP71:	 CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R0,A
	 INC R0
	 INC DPTR
	 CJNE R0,#34H,LP71
	 MOV R0,#30H
	  POP DPH
	 POP DPL
	 RET
	 
	 
LOOP72:	 PUSH DPL
         PUSH DPH
	 MOV R1,#34H
LP72:	 CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R1,A
	 INC R1
	 INC DPTR
	 CJNE R1,#34H,LP72
	 MOV R1,#34H
	 POP DPH
	 POP DPL
	 RET

	 
;-------OUTPUT 8-------------	 
OP8: LCALL BLANK	;ROLLING MESSAGE INSIDE TO OUTSIDE
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 MOV R0,#33H
	 MOV R1,#34H
	 MOV R2,#3H
	 MOV R3,#4H
	 CLR C
   LOOP8:	MOV A,R2
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R0,A
	 MOV A,R3	
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R1,A
	 DEC R0
	 INC R1
	 DEC R2
	 INC R3
	 LCALL DELAY
	 CJNE R3,#08H,LOOP8
	 SJMP OP8
	 
BLANK:MOV R0,#30H		;SHOW BLANK MESSAGE
   A1:MOV @R0,#0FFH
	 INC R0
	 CJNE R0,#38H,A1
	 RET

DISPLAY: MOV R0,#37H; previous was 30h
	 PUSH DPL
	 PUSH DPH
   DISP1:CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A				;DATA IS IN COMMON ANODE
	 MOV @R0,A
	 DEC R0 ; previous was inc
	 INC DPTR
	 CJNE R0,#2FH,DISP1 ; 38H
	 POP DPH
	 POP DPL
	 RET

DELAY:	 MOV R5,#90     ;0.756S DELAY FOR KEY CHECKING
   DELAY1: MOV R6,#200
   DELAY2: MOV R7,#5		
   SWITCH1:MOV A,P1			
	       CJNE A,#0FEH,SWITCH2
	       LCALL DEBOUNCE
	       POP 25H		;STAC POINTER DEC. BY 2
	       POP 26H	
	       LJMP OP1
   SWITCH2:MOV A,P1
	       CJNE A,#0FDH,SWITCH3
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP2
   SWITCH3:MOV A,P1
	       CJNE A,#0FBH,SWITCH4
	       POP 25H
	       POP 26H
	       LJMP OP3
   SWITCH4:MOV A,P1
	       CJNE A,#0F7H,SWITCH5
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP4
   SWITCH5:MOV A,P1
	       CJNE A,#0EFH,SWITCH6
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP5
   SWITCH6:MOV A,P1
	       CJNE A,#0DFH,SWITCH7
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP6
   SWITCH7:MOV A,P1
	       CJNE A,#0BFH,SWITCH8
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP7
   SWITCH8:MOV A,P1
	       CJNE A,#7FH,SWITCH9
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP8
  SWITCH9: DJNZ R7,$
		   DJNZ R6,DELAY2
		   DJNZ R5,DELAY1
		   RET
		
DEBOUNCE:MOV R5,#250		;20mS DELAY
      DEBOUNCE1:MOV R6,#40
		DJNZ R6,$
		DJNZ R5,DEBOUNCE1
		RET

MSG0: DB "::PUSH::"

MSG1: DB "BE-3 2025"

MSG2: DB "::::::::ELECTRIC::::::::"

MSG3: DB "ELEC::::"

MSG4: DB "::::TRIC"
 
SEVSEG:INC A
	  MOVC A,@A+PC
	  RET		;ALL DATA IN COMMON CATHODE
	  DB 3FH	;0
	  DB 06H	;1
	  DB 5BH	;2
	  DB 4FH	;3
	  DB 66H	;4
	  DB 6DH	;5
	  DB 7DH	;6
	  DB 07H	;7	
	  DB 7FH	;8
	  DB 6FH	;9
	  DB 00H
	  DB 00H
	  DB 00H
	  DB 00H
	  DB 00H
	  DB 00H
	  DB 00H
	  DB 77h	;A
	  DB 7CH	;B
	  DB 39H	;C
	  DB 5EH	;D
	  DB 79H	;E
	  DB 71H	;F
	  DB 3DH	;G
	  DB 76H	;H
	  DB 30H	;I
	  DB 1EH	;J
	  DB 75H	;K
	  DB 38H	;L
	  DB 37H	;M
	  DB 54H	;N
	  DB 3FH	;O
	  DB 73H	;P
	  DB 67H	;Q
	  DB 50H	;R
	  DB 6DH	;S
	  DB 78H	;T
	  DB 3EH	;U
	  DB 1CH	;V
	  DB 2AH	;W
	  DB 76H	;X
	  DB 6EH	;Y
	  DB 5BH	;Z
END
