ORG 0000H
   LJMP MAIN
ORG 000BH			;INTERRUPT TIMER0
	 MOV TH0,#0F6H  ;DELAY FOR INTERUPPT 2.5mS
	 MOV TL0,#3CH
	 PUSH PSW
	 PUSH ACC
	 CLR RS1	
	 SETB RS0 		; RB1
	 MOV P2,R2		;SELECT NO. OF LED
	 MOV P0,@R0		;DATA WHICH HAS TO BE SHOWN ON LED
	 INC R0
	 CJNE R0,#38H,L1
	 MOV R0,#30H
	 
	 
	 
L1: MOV A,R2
	RL A
	MOV R2,A 
	POP ACC
	POP PSW
	RETI 
	 
MAIN:MOV SP,#50H
	 MOV TMOD,#01H		;TIMER0
	 MOV TH0,#0F6H		;DELAY FOR INTERUPPT 2.5mS
	 MOV TL0,#3CH
	 MOV 08H,#30H
	 MOV 0AH,#01H
	 SETB TR0
	 SETB ET0
	 SETB EA
;-------OUTPUT 0--------
OP0: MOV DPTR,#MSG0
	 LCALL DISPLAY
	 LCALL SWITCH1
	 SJMP OP0
;-------OUTPUT 1--------	 
OP1: MOV DPTR,#MSG1		;STEADY MESSAGE
	 LCALL DISPLAY
	 LCALL SWITCH1
	 SJMP OP1
;-------OUTPUT 2-------------
OP2: MOV DPTR,#MSG1		;BLINKING MESSAGE
	 LCALL DISPLAY
	 LCALL DELAY
	 LCALL BLANK
	 LCALL DELAY
	 SJMP OP2
;-------OUTPUT 3-------------	 
OP3: MOV DPTR,#MSG2		;ROLLING THROUGH LEFT
	 ;MOV A,DPH
	 CLR C
	 SUBB A,#16		
	 MOV DPH,A
	 MOV A,DPL
	 SUBB A,#00H
	 MOV DPL,A
	 MOV R3,#16
   LOOP3: 	 LCALL DISPLAY
	 LCALL DELAY
	 CLR C
     DEC DPL
     MOV A,DPH
     SUBB A,#00B
     MOV DPH,A
	 DJNZ R3,LOOP3
	 SJMP OP3
;-------OUTPUT 4-------------	  
OP4: MOV DPTR,#MSG2		;ROLLING THROUGH RIGHT
	 ;MOV R3,#16
   LOOP4:	 LCALL DISPLAY
	 LCALL DELAY
	 INC DPTR
	 DJNZ R3,LOOP4
	 SJMP OP4  
;-------OUTPUT 5-------------	 
OP5: MOV DPTR,#MSG1		;ODD NO. LED BLINKING OTHER'S STEADY
	 LCALL DISPLAY
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 LCALL BLANK
	 MOV R0,#31H
	 MOV R2,#01H
   LOOP5:	 LCALL DONE5
	 CJNE R2,#09H,LOOP5
	 LCALL DELAY
	 SJMP OP5
   DONE5:	 MOV A,R2
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R0,A
	 INC R0
	 INC R0
	 INC R2
	 INC R2
	 RET	 
;-------OUTPUT 6-------------	 
OP6: MOV DPTR,#MSG1		; EVEN NO. LED BLINKING OTHER'S STEADY
	 LCALL DISPLAY
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 LCALL BLANK
	 MOV R0,#30H
	 MOV R2,#00H
   LOOP6:	 LCALL DONE5
	 CJNE R2,#08H,LOOP6
	 LCALL DELAY
	 SJMP OP6
;-------OUTPUT 7------------- 
OP7:	 ;ROLLING MESSAGE OUTSIDE TO INSIDE
	 LCALL DELAY
	 MOV DPTR,#MSG3
	 MOV 22H,#5
	 MOV A,DPL
	 ADD A,#4
	 MOV DPL,A
	 MOV 20H,DPL
	 MOV DPTR,#MSG4
	 MOV 21H,DPL
 HARDIK:MOV DPL,20H
	 LCALL LOOP71
	 MOV DPL,21H
	 LCALL LOOP72
	 DEC 20H
	 INC 21H
	 LCALL DELAY
	 DJNZ 22H,HARDIK
	 LCALL DELAY
	 SJMP OP7
	 
LOOP71:PUSH DPL
	    PUSH DPH
	    MOV R0,#30H
LP71:	 CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R0,A
	 INC R0
	 INC DPTR
	 CJNE R0,#34H,LP71
	 MOV R0,#30H
	  POP DPH
	 POP DPL
	 RET
	 
	 
LOOP72:	 PUSH DPL
         PUSH DPH
	 MOV R1,#34H
LP72:	 CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 CPL A
	 MOV @R1,A
	 INC R1
	 INC DPTR
	 CJNE R1,#34H,LP72
	 MOV R1,#34H
	 POP DPH
	 POP DPL
	 RET

	 
;-------OUTPUT 8-------------	 
OP8: LCALL BLANK	;ROLLING MESSAGE INSIDE TO OUTSIDE
	 LCALL DELAY
	 MOV DPTR,#MSG1
	 MOV R0,#33H
	 MOV R1,#34H
	 MOV R2,#3H
	 MOV R3,#4H
	 
   LOOP8:CLR C	
   		MOV A,R2
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 ;CPL A
	 MOV @R0,A
	 MOV A,R3	
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 ;CPL A
	 MOV @R1,A
	 INC R0 ;decc
	 DEC R1 ; INC
	 INC R2 ;DEC
	 DEC R3 ;INC
	 LCALL DELAY
	 CJNE R3,#07FH,LOOP8; 08H
	 SJMP OP8
	 
BLANK:MOV R0,#30H		;SHOW BLANK MESSAGE
   A1:MOV @R0,#0FFH
	 INC R0
	 CJNE R0,#38H,A1
	 RET

DISPLAY: MOV R0,#37H; previous was 30h
	 ;PUSH DPH		
	 ;PUSH DPL
   DISP1:CLR A
	 MOVC A,@A+DPTR
	 CLR C
	 SUBB A,#30H
	 LCALL SEVSEG
	 ;CPL A				;DATA IS IN COMMON ANODE
	 MOV @R0,A
	 DEC R0 ; previous was inc
	 INC DPTR
	 CJNE R0,#2FH,DISP1 ; 38H
	 ;POP DPL
	 ;POP DPH
	 RET

DELAY:	 MOV R5,#90     ;0.756S DELAY FOR KEY CHECKING
   DELAY1: MOV R6,#200
   DELAY2: MOV R7,#5		
   SWITCH1:MOV A,P1			
	       CJNE A,#0FEH,SWITCH2
	       LCALL DEBOUNCE
	       POP 25H		;STAC POINTER DEC. BY 2
	       POP 26H	
	       LJMP OP1
   SWITCH2:MOV A,P1
	       CJNE A,#0FDH,SWITCH3
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP2
   SWITCH3: CJNE A,#0FBH,SWITCH4; mov before cjne
		   MOV A,P1
	       POP 25H
	       POP 26H
	       LJMP OP3
   SWITCH4:MOV A,P1
	       CJNE A,#0F7H,SWITCH5
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP4
   SWITCH5:MOV A,P1
	       CJNE A,#0EFH,SWITCH6
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP5
   SWITCH6:MOV A,P1
	       CJNE A,#0DFH,SWITCH7
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP6
   SWITCH7:MOV A,P1
	       CJNE A,#0BFH,SWITCH8
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP7
   SWITCH8:MOV A,P1
	       CJNE A,#7FH,SWITCH9
	       LCALL DEBOUNCE
	       POP 25H
	       POP 26H
	       LJMP OP8
  SWITCH9: DJNZ R7,$
		   DJNZ R6,DELAY2
		   DJNZ R5,DELAY1
		   RET
		
DEBOUNCE:MOV R5,#250		;20mS DELAY
      DEBOUNCE1:MOV R6,#40
		DJNZ R6,$
		DJNZ R5,DEBOUNCE1
		RET

MSG0: DB "::PUSH::"

MSG1: DB "ELECTRIC"

MSG2: DB "::::::::ELECTRIC::::::::"

MSG3: DB "ELEC::::"

MSG4: DB "::::TRIC"
 
SEVSEG:INC A
	  MOVC A,@A+PC
	  RET		;ALL DATA IN COMMON ANODE
DB 0C0H;0
DB 0CFH;1
DB 0A4H;2
DB 0B0H;3
DB 99H;4
DB 92H;5
DB 82H;6
DB 0F8H;7
DB 80H;8
DB 90H;9
DB 0FFH
DB 0FFH
DB 0FFH
DB 0FFH
DB 0FFH
DB 0FFH
DB 0FFH
DB 88H;A
DB 80H;B
DB 0C6H;C
DB 0A1H;D
DB 86H;E
DB 8EH;F
DB 0C2H;G
DB 89H;H
DB 0CFH;I
DB 0F1H;J
DB 8AH;K
DB 0C7H;L
DB 0AAH;M
DB 0C8H;N
DB 0C0H;O
DB 8CH;P
DB 98H;Q
DB 0CEH;R
DB 92H;S
DB 87H;T
DB 0C1H;U
DB 0D5H;V
DB 99H;W
DB 0B6H;X
DB 91H;Y
DB 0A4H;Z
END
